TOTAL. IMPULSE. DEATH.
StarCoreSE/SCModRepository pull request #1138
Opened 2024-05-02 03:51 UTC by InvalidArgument3

2024-05-02 03:51 UTC, Jnick-24 commented
i wish i were as cool as this commit

2024-05-02 03:56 UTC, Jnick-24 requested changes
wow this looks good except for the 1 mass

# **TOTAL. IMPULSE. DEATH.**

2024-05-02 04:28 UTC, CommodoreChet commented
Revert Changes made to NHI before Merging this.

2024-05-02 09:39 UTC, Tiberias42 commented
Way to hard to read on my phone, will get on when I'm home from work.

2024-05-02 12:19 UTC, BadM0dder commented
Hah funny meme I'll just revert tio changes next pull :whenstarcore:

2024-05-02 23:14 UTC, TaitKaito commented
Send it for Fletcher boys, TOTAL IMPULSE DEATH LESSGOOOO

2024-05-02 23:37 UTC, Tiberias42 approved these changes
I looked at the Serpent Arms.  I'm sure we have a perfectly good reason to make every bullet that had no weight at all 1 kg.  I am ok with this for SA.

2024-05-03 03:22 UTC, Jnick-24 commented
Okay, just as a personal reference - what guns would you guys consider to "need" impulse? Aries, hunter pan, etc?

2024-05-03 03:39 UTC, CommodoreChet requested changes

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Experimental/EXP_BFG_Ammo_Cannon_Ammo.cs
Revert - Not on Active Roster

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Fixed/NHI_Fixed_Torpedo_Launcher_Ammo.cs
Revert - Not on Active Roster

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Starcore/SC_Coil_Cannon_Ammo.cs
Revert
Changes Already Planned to Correct Shield Behavior

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Flak_Cannon_Turret_Ammo.cs
Revert - Not on Active Roster

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Heavy_Gun_Turret_Ammo.cs
Revert
Mass on Primary Round is irrelevant as the round is Prox Fused. Change Unnecessary.

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Heavy_Railgun_Turret_Ammo.cs
Revert - Not on Active Roster

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Kinetic_Cannon_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Light_Autocannon_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Light_Railgun_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Mk1_Cannon_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues
There are Misc. Disabled Ammos in this File that should not be altered.

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Mk2_Cannon_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues
There are Misc. Disabled Ammos in this File that should not be altered.

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_Mk3_Cannon_Turret_Ammo.cs
Revert
This Round was Properly Balanced and has not shown any Issues
There are Misc. Disabled Ammos in this File that should not be altered.

2024-05-03 03:39 UTC, CommodoreChet commented on Weapon Mods/Stable/NorseHeavyIndustries/Data/Scripts/Coreparts/NHI_Turreted/NHI_PD_Turret_Ammo.cs
Revert
Round is Prox Fused and does not target Large Grids | Mass is not relevant to Starcore Balance, Required for Internal Consistency

2024-05-03 04:05 UTC, InvalidArgument3 commented
wait fuck

2024-05-08 00:45 UTC, InvalidArgument3 commented
not gonna modify 300 cs files for this

2024-05-08 00:45 UTC, closed without merging